name: Deploy Hapax Finder to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      # Step 3: Add DigitalOcean to known hosts
      - name: Add DigitalOcean to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

      # Step 4: Deploy using rsync
      - name: Deploy to DigitalOcean
        env:
          DEPLOY_PATH: /var/www/peterchinman.com/hapax-finder
        run: |
          # make directory if it doesn't exist already
          ssh root@${{ secrets.DROPLET_IP }} "\
            mkdir -p $DEPLOY_PATH"

          rsync -avz --delete \
            --exclude=".git" \
            ./ root@${{ secrets.DROPLET_IP }}:$DEPLOY_PATH

          # SSH into the server for post-deployment tasks
          ssh root@${{ secrets.DROPLET_IP }} "\
            # Install dependencies using Composer
            if [ -f $DEPLOY_PATH/composer.json ]; then
              cd /var/www/peterchinman.com/hapax-finder
              composer install --no-interaction --no-dev --optimize-autoloader
            fi

            # Set permissions and reload the server
            chown -R www-data:www-data $DEPLOY_PATH && \
            chmod -R 755 $DEPLOY_PATH && \
            systemctl reload apache2"
